language: ruby
rvm:
  - 2.1
install: bundle install
script: bundle exec jekyll build
deploy:
  provider: script
  script: find . -type f -exec curl -k -u $FTP_USERNAME:$FTP_PASSWORD --ftp-create-dirs -T {} sftp://$FTP_HOST/$FTP_PATH {} \;
  on:
    branch: master
