language: ruby
rvm:
  - 2.1
install: bundle install
script: bundle exec jekyll build
deploy:
  skip_cleanup: true
  provider: script
  script: bundle exec travis-custom-deploy sftp service:jekyll
  on:
    branch: master
