# Setup
title:        Mailu
tagline:      Insular e-mail distribution
baseurl:      ""
exclude:
  - Gemfile
  - Gemfile.lock

# About/contact
author:
  name:       Mailu contributors
  url:        https://github.com/Mailu/

# Main links
links:
  doc:        https://github.com/Mailu/Mailu/wiki
  setup:      https://github.com/Mailu/Mailu/wiki/Setup-Guide
  github:     https://github.com/Mailu/Mailu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
