# Setup
title:        Freeposte.io
tagline:      Simple yet full-featured mail server as a set of Docker images
baseurl:      ""
exclude:
  - Gemfile
  - Gemfile.lock

# About/contact
author:
  name:       kaiyou
  url:        https://kaiyou.fr

# Main links
links:
  doc:        https://github.com/kaiyou/freeposte.io/wiki
  setup:      https://github.com/kaiyou/freeposte.io/wiki/Setup-Guide
  github:     https://github.com/kaiyou/freeposte.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
